### ISSUE TITLE
Hard coded github.com/Robert-Frampton/metal-ssg-docs in links

### ISSUE THREAD

**Issue by blzaugg** [liferay/electricjs.com#17]
All pages.

> Contribute to this Doc on Github! [Edit this section](https://github.com/Robert-Frampton/metal-ssg-docs/tree/master/src/pages/docs/layouts.md).

**Comment by zenorocha** [comment]
@Robert-Frampton I think we need to add another question on the generator that asks for the repository name.

**Comment by Robert-Frampton** [comment]
The generator actually sniffs out the git user info and adds it to the generated `package.json` file. In   this case I just forgot to rename the repo [here](https://github.com/liferay/electricjs.com/blob/master/package.json#L7). I'll change it now.

**Comment by zenorocha** [comment]
Perfect! You may also include this data here (https://github.com/liferay/generator-electric/commit/27c582cbba2d6edd59fb3ae7cecc1a6b8620a950#diff-59fcdb862e7a960e358111738efa84e4R38).

**Comment by zenorocha** [comment]
https://github.com/liferay/electricjs.com/commit/86e75550fecf14b218c50fa975afc316ffa5c7d0
