### ISSUE TITLE
Does this generate static or dynamic sites?

### ISSUE THREAD

**Issue by blzaugg** [liferay/electricjs.com#7]
NOTE: This is input from Byran's Electric introduction experience. I will be intentionally ignorant.

On page: http://electricjs.com/

First we say:
> Electric is a Node.js **static** generator that ...

Later we say:
> Transform plain text into **dynamic** sites ...

Again, later, we say:
> Eletric builds completely **static** HTML sites ...

*Added bolding for emphasis

**Comment by zenorocha** [comment]
Good catch!
